[workspace]
resolver = "2"
members = [
    "crates/pb_core",
    "crates/pb_storage",
    "crates/pb_service",
    "crates/pb_ipc",
    "crates/pb_sidecar",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.43", features = ["full"] }
thiserror = "2.0"
anyhow = "1.0"
rusqlite = { version = "0.33", features = ["bundled"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
chrono = { version = "0.4", features = ["serde"] }
redis = { version = "1.7.0", default-features = false, features = ["tokio-comp", "aio"] }
uuid = { version = "1", features = ["v4"] }
tempfile = "3"

# Internal Workspace Crates
pb_core = { path = "crates/pb_core" }
pb_storage = { path = "crates/pb_storage" }
pb_service = { path = "crates/pb_service" }
pb_ipc = { path = "crates/pb_ipc" }
pb_sidecar = { path = "crates/pb_sidecar" }

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "unwind"
strip = true
