[package]
name = "pb_service"
version = "0.1.8"
edition = "2021"

[dependencies]
pb_core = { workspace = true }
pb_storage = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
redis = { workspace = true }
